In [1]:
import numpy as np

In [2]:
a = np.array([3, 1, 5, 6])
a

array([3, 1, 5, 6])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([[3, 1, 5, 6]])
a

array([[3, 1, 5, 6]])

In [5]:
a.shape

(1, 4)

In [6]:
a = np.array([[[3, 1, 5, 6]]])
a

array([[[3, 1, 5, 6]]])

In [7]:
a.shape

(1, 1, 4)

In [8]:
a.flatten()

array([3, 1, 5, 6])

In [9]:
a = np.array([
    [3, 1, 5, 6],
    [4, 5, 7, 2],
])
a

array([[3, 1, 5, 6],
       [4, 5, 7, 2]])

In [10]:
a.shape

(2, 4)

In [11]:
a = np.array([3, 1, 5, 6])
a

array([3, 1, 5, 6])

In [12]:
a + 10

array([13, 11, 15, 16])

In [13]:
a = np.array([
    [3, 1, 5, 6],
    [4, 5, 7, 2],
])
a + 10

array([[13, 11, 15, 16],
       [14, 15, 17, 12]])

In [18]:
a = np.array([3, 1, 5, 6])
2 ** a 

array([ 8,  2, 32, 64])

In [19]:
a = np.array([3, 1, 5, 6])
a.T

array([3, 1, 5, 6])

In [22]:
a = np.array([3, 1, 5, 6])
b = np.array([3, 1, 5, 6])
a.dot(b)

np.int64(71)

In [21]:
a @ b # dot product

np.int64(71)

In [25]:
a = np.array([3, 1, 5, 6])
b = np.array([3, 1, 5, 6])
((a - b) ** 2).sum()

np.int64(0)

In [26]:
a = np.array([3, 0, 5, 6])
b = np.array([3, 1, 5, 6])
((a - b) ** 2).sum()

np.int64(1)

In [27]:
a = np.array([3, 0, 5, 6])
a[:3]

array([3, 0, 5])

In [46]:
a = np.random.randint(0, 10, (4, 6))
a

array([[1, 0, 1, 9, 0, 5],
       [9, 8, 3, 9, 9, 1],
       [8, 7, 5, 1, 3, 3],
       [8, 5, 6, 5, 9, 2]])

In [62]:
np.random.seed(1000)
a = np.random.randint(0, 10, (4, 6))
a

array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])

In [64]:
a = np.array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])
a

array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])

In [65]:
a[0]

array([3, 7, 7, 0, 1, 0])

In [66]:
a[:,0]

array([3, 9, 4, 2])

In [67]:
a[:2]

array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4]])

In [68]:
a[[0, 2]]

array([[3, 7, 7, 0, 1, 0],
       [4, 2, 9, 8, 2, 4]])

In [69]:
a[[0, 2, 0,0]]

array([[3, 7, 7, 0, 1, 0],
       [4, 2, 9, 8, 2, 4],
       [3, 7, 7, 0, 1, 0],
       [3, 7, 7, 0, 1, 0]])

In [72]:
a

array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])

In [71]:
a[:, [0, 2]]

array([[3, 7],
       [9, 9],
       [4, 9],
       [2, 5]])

In [73]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [74]:
np.diag([4, 5, 7, 2, 1])

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [75]:
np.zeros((4, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
np.ones((4, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [77]:
a = np.array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])
a

array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])

In [78]:
a.sum()

np.int64(110)

In [79]:
a.sum(axis = 1)

array([18, 43, 29, 20])

In [80]:
a.sum(axis = 0)

array([18, 22, 30, 16, 12, 12])

In [81]:
a = np.array([4, 5, 7, 2, 1])
a.mean()

np.float64(3.8)

In [82]:
a.sum()/len(a)

np.float64(3.8)

In [90]:
# standard deviation
(((a - a.mean()) ** 2).sum()/(len(a)-1)) ** 0.5

np.float64(2.3874672772626644)

In [88]:
np.std(a)

np.float64(2.1354156504062622)

In [89]:
(((a - a.mean()) ** 2).sum()/(len(a))) ** 0.5

np.float64(2.1354156504062622)

In [91]:
a = np.array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])
a

array([[3, 7, 7, 0, 1, 0],
       [9, 8, 9, 4, 9, 4],
       [4, 2, 9, 8, 2, 4],
       [2, 5, 5, 4, 0, 4]])

In [92]:
b = np.array([3, 4, 2, 6])

In [93]:
a.dot(b)

ValueError: shapes (4,6) and (4,) not aligned: 6 (dim 1) != 4 (dim 0)

In [94]:
b.dot(a)

array([ 65,  87, 105,  56,  43,  48])

In [95]:
a = np.arange(6).reshape((2, 3)) 

In [97]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
np.vstack([a, a])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [98]:
np.hstack([a, a])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [99]:
a = np.array([[10, 20, 30],
       [40, 50, 60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [100]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [107]:
a + b

array([[11, 22, 33],
       [41, 52, 63]])

In [102]:
b.reshape((1, 3))

array([[1, 2, 3]])

In [106]:
a + b.reshape((1, 3))

array([[11, 22, 33],
       [41, 52, 63]])

In [121]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
b = np.array([1, 2])
a + b.reshape((2, 1))

array([[11, 21, 31],
       [42, 52, 62]])

In [117]:
a.shape

(2, 3)

In [118]:
b.shape

(2,)